### ISSUE TITLE
[error] Unable to execute slp_utils.execute_slp_claim

### ISSUE THREAD

**Issue by YuMurata** [ZracheSs-xyZ/PayoutScript-xyZ#3]
Hi, there.
I want to send SLP to scholars with these GREAT scripts.
But, I can't send because error is occured.
Do you know the solution?

---

### as is

Unable to execute slp_utils.execute_slp_claim

### to be

execute slp_utils.execute_slp_claim

### environment

```bash
$ wsl lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$ wsl python3 --version
Python 3.8.10

$ wsl pip show web3
Name: web3
Version: 5.23.0
```

### to reproduce
```bash
$ wsl python3 PayoutScript-xyZ.py /path/to/my/slp-payout-config.json

*** Welcome to the SLP Payout program *** (2021-08-27 01:43:11.207580)
Checking for unclaimed SLPAccount 'My Name' (nonce: 0) has 10 unclaimed SLP.
Would you like to claim SLP? y
   Claiming 10 SLP for 'My Name'...Traceback (most recent call last):
  File "PayoutScript-xyZ.py", line 115, in <module>
    slp_utils.execute_slp_claim(slp_claim, nonces)
  File "/path/to/project/PayoutScript-xyZ/slp_utils.py", line 47, in execute_slp_claim
    claim.state["signature"] = result["signature"].replace("0x", "")
TypeError: 'NoneType' object is not subscriptable
```

### frequency
5/5

### investigated
https://github.com/ZracheSs-xyZ/PayoutScript-xyZ/blob/main/slp_utils.py#L41

my response.json() is ...

```
{'blockchain_related': {'balance': 10,
                        'block_number': 6139656,
                        'checkpoint': 0,
                        'signature': None},
 'claimable_total': 10,
 'client_id': '0xb99af3eb1b8782b019695f6b1a2b7c4268da855d',
 'item': {'created_at': 1576669291,
          'description': 'Breeding Potion is required to breed two Axies',
          'id': 1,
          'image_url': '',
          'name': 'Breeding Potion',
          'updated_at': 1576669291},
 'item_id': 1,
 'last_claimed_item_at': 0,
 'success': True,
 'total': 10}
```

`blockchain_related.signature` is None, I don't know the cause ...

**Comment by YuMurata** [comment]
Hi.
I solved this issue.

It seems that an error can occur if the server takes too long to process the complaint.
I succeeded in sending after repeating the execution several times.

**Comment by ZracheSs-xyZ** [comment]
Sorry for the very late response here.
I fixed this issue by making the script more stable!

Don't try it right now though as SM restrain certain endpoint used by the script because Ronin Network is too congested already!
